services:
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: mb-auth-service
    secrets:
      - source: PORT_AUTH
        target: PORT
      - source: CORS_ORIGIN_AUTH
        target: CORS_ORIGIN
      - source: JWT_SECRET
        target: JWT_SECRET
      - source: MOCK_AUTH_USERNAME
        target: MOCK_AUTH_USERNAME
      - source: MOCK_AUTH_PASSWORD
        target: MOCK_AUTH_PASSWORD
    ports:
      - "4001:4001"

  market-service:
    build:
      context: ./backend/market-service
      dockerfile: Dockerfile
    container_name: mb-market-service
    secrets:
      - source: PORT_MARKET
        target: PORT
      - source: CORS_ORIGIN_MARKET
        target: CORS_ORIGIN
    ports:
      - "4002:4002"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_AUTH_API_URL: https://exam_auth_service-senjamirv.pitunnel.com
        NEXT_PUBLIC_MARKET_API_URL: https://exam_market_service-senjamirv.pitunnel.com
        NEXT_PUBLIC_MARKET_WS_URL: wss://exam_market_service-senjamirv.pitunnel.com/ws
        NEXT_PUBLIC_HISTORY_CACHE_TTL_MS: 30000
    container_name: mb-frontend
    secrets:
      - source: AUTH_API_URL
        target: AUTH_API_URL
      - source: PORT_FRONTEND
        target: PORT
      - source: HOSTNAME_FRONTEND
        target: HOSTNAME
    ports:
      - "3110:3110"
    depends_on:
      - auth-service
      - market-service

secrets:
  AUTH_API_URL:
    file: ./secrets/AUTH_API_URL
  PORT_AUTH:
    file: ./secrets/PORT_AUTH
  CORS_ORIGIN_AUTH:
    file: ./secrets/CORS_ORIGIN_AUTH
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  MOCK_AUTH_USERNAME:
    file: ./secrets/MOCK_AUTH_USERNAME
  MOCK_AUTH_PASSWORD:
    file: ./secrets/MOCK_AUTH_PASSWORD
  PORT_MARKET:
    file: ./secrets/PORT_MARKET
  PORT_FRONTEND:
    file: ./secrets/PORT_FRONTEND
  HOSTNAME_FRONTEND:
    file: ./secrets/HOSTNAME_FRONTEND
  CORS_ORIGIN_MARKET:
    file: ./secrets/CORS_ORIGIN_MARKET
